### ISSUE TITLE
setting up using docker-compose | help needed

### ISSUE THREAD

**Issue by albjeremias** [Parkour-Vienna/distrust#5]
yay.. nice project :) 
but its lacking some documentation. I want to try to help.

questions about the distrust.yml file:
`listenAddr: 0.0.0.0:3000`
This is the address to listen to all requests to login?

Can I re-use the same private key that you posted on this repository? How can I generate my own private key?

What means allow_groups ? 

thanks! :) I want to be able to use discourse as a open id provider.. to connect to nextcloud.. and later to mastodon/peertube... :)

**Comment by albjeremias** [comment]
making progress: https://github.com/ory/fosite will read this

**Comment by theSuess** [comment]
Sorry for the late response,
the listenAddr is used by the server to bind to a port.

`allowGroups` can be used to restrict the client to discourse groups (e.g you only want team members to use nextcloud).

When configuring nextcloud you must configure the `oidc_login_provider_url`.
It should be: `https://your-auth-server/oauth2`

If you want to generate a private key run `./distrust genkey`

**Comment by albjeremias** [comment]
will test and give feedback.. thank ya.. amazing work!! \o/ juhuuuu been waiting for this for weeks.

**Comment by albjeremias** [comment]
I get this on the logfile of distrust:

```
openid_distrust_1 is up-to-date
Attaching to openid_distrust_1
distrust_1  | 3:29PM INF clients loaded numClients=1
distrust_1  | 3:29PM INF Starting server url=http://0.0.0.0:3000
distrust_1  | 3:30PM TRC request finished duration=0.024997 from=192.168.16.1:43026 method=GET path=/ status=307
distrust_1  | 3:31PM TRC request finished duration=0.046828 from=192.168.16.1:45780 method=GET path=/.wellknown/ status=404
distrust_1  | 3:34PM INF clients loaded numClients=1
distrust_1  | 3:34PM INF Starting server url=http://0.0.0.0:3000
distrust_1  | 3:34PM TRC request finished duration=0.014457 from=192.168.16.1:49586 method=GET path=/.well-known/openid-configuration status=404
distrust_1  | 5:54PM TRC request finished duration=0.225272 from=192.168.16.1:36438 method=GET path=/ status=307
distrust_1  | 3:59PM TRC request finished duration=6.829464 from=192.168.16.1:54070 method=GET path=/ status=307
distrust_1  | 4:00PM TRC request finished duration=2.605694 from=192.168.16.1:54182 method=GET path=/oauth2 status=404
distrust_1  | 4:00PM TRC request finished duration=0.038773 from=192.168.16.1:57194 method=GET path=/oauth2 status=404
```  
the 192.168.16.1 is the gateway.. but it doesnt matter much in here..

**Comment by theSuess** [comment]
It looks like nextcloud is still configured wrong. It should try to use `/oauth2/.well-known/openid-configuration`

**Comment by albjeremias** [comment]
When i go to
https://discourseserver/oauth2/.well-known/openid-configuration
I get 
"404 / Not found"

**Comment by theSuess** [comment]
For the consumers (nextcloud etc) you need to specify the `distrust` url, not the `discourse` url since the distrust server acts on its own and does no register routes with discourse

**Comment by albjeremias** [comment]
ill close this. and open a new one. hope you can still answer me
